import time
import traceback

import aiofiles
from PIL import Image, ImageDraw

from ...config import *
from ..domain.models.song import Song
from ..service import mai
from .base import ScoreBaseImage
from .tools import *


class UpdateTable:
    
    _type_bg = {
        "SD": Image.open(pic_dir / "SD.png").convert("RGBA"),
        "DX": Image.open(pic_dir / "DX.png").convert("RGBA")
    }
    _dx_small_bg = _type_bg["DX"].resize((44, 16))
    _diff_bg = [Image.new("RGBA", (75, 16), color) for color in ScoreBaseImage._bg_color]
    
    def __init__(self):
        self.lv_list = LEVEL_LIST[6:]
    
    def _generate_rating_bg(self, height: int) -> Image.Image:
        """生成背景"""
        im = tricolor_gradient_prism_plus(1400, height)
        im.alpha_composite(ScoreBaseImage._aurora_bg)
        im.alpha_composite(ScoreBaseImage._shines_bg, (11, 6))
        im.alpha_composite(ScoreBaseImage._cloud_bg, (318, height - 545))
        im.alpha_composite(ScoreBaseImage._rainbow_bottom_bg, (122, height - 305))
        for h in range((height // 358) + 1):
            im.alpha_composite(ScoreBaseImage._pattern_bg, (0, (358 + 7) * h))
        im.alpha_composite(ScoreBaseImage._separator_bg, (100, 200))
        return im
    
    async def _save_image(self, im: Image.Image, path: Path):
        """保存图片到本地"""
        by = BytesIO()
        im.save(by, "PNG")
        async with aiofiles.open(path, "wb") as f:
            await f.write(by.getbuffer())
    
    async def update_level_15_rating_table(self):
        """单独绘制等级 15的定数表"""
        draw_time = time.time()
        lv15 = mai.total_level_data["15"]["15.0"]
        count = len(lv15)
        lines = (count // 3) + (1 if count % 3 else 0)
        height = 550 + lines * 450
        
        im = self._generate_rating_bg(height)
        
        font_color = (114, 188, 254, 255)
        dr = ImageDraw.Draw(im)
        fot = DrawText(dr, FOTNEWRODIN)
        
        fot.draw(495, 160, 70, "Level.", font_color, "ld", 8, (255, 255, 255, 255))
        fot.draw(750, 160, 100, "15", font_color, "ld", 8, (255, 255, 255, 255))
        fot.draw(
            700, height - 75, 30, 
            f"Designed by Yuri-YuzuChaN & BlueDeer233.", 
            font_color, "mm"
        )
        fot.draw(
            700, height - 30, 30, 
            f"Generated by {maiconfig.botname} BOT", 
            font_color, "mm"
        )
        
        unknown_chart = Image.open(song_chart(0)).convert("RGBA").resize((330, 330))
        for i in range(lines * 3):
            row = i // 3
            col = i % 3
            
            x = 100 + col * 425
            y = 400 + row * 450
            
            im.alpha_composite(ScoreBaseImage._chart_white_bg, (x, y))
            if i < count:
                song = lv15[i]
                chart = Image.open(song_chart(song.song_id)).convert("RGBA")
                im.alpha_composite(chart.resize((330, 330)), (x + 10, y + 10))
                im.alpha_composite(self._type_bg[song.type], (x + 200, y + 345))
                im.alpha_composite(
                    Image.open(pic_dir / f"{song.version_str}.png").resize((208, 100)), 
                    (x + 71, y - 50)
                )
                fot.draw(x + 100, y + 370, 35, song.song_id, font_color, "mm")
            else:
                im.alpha_composite(unknown_chart, (x + 10, y + 10))
                im.alpha_composite(self._type_bg["DX"], (x + 200, y + 345))
                fot.draw(x + 100, y + 370, 35, "????", font_color, "mm")
                fot.draw(x + 175, y + 280, 30, "UNKNOWN", font_color, "mm", 8, (255, 255, 255, 255))
        
        await self._save_image(im, rating_dir / "15.png")
        log.info(f"lv.15 定数表更新完成，耗时：{time.time() - draw_time}s")
    
    async def update_rating(self):
        """绘制定数表"""
        for lv in self.lv_list[:-1]:
            single_time = time.time()
            lvlist = mai.total_level_data[lv]
            lines = 0
            for _l in lvlist:
                music_num = len(lvlist[_l])
                if music_num == 0:
                    count = 1
                else:
                    remainder = music_num % 14
                    count = (music_num // 14) + (1 if remainder else 0)
                lines += count

            if "+" in lv:
                ds_count = 4
            elif lv == "6":
                ds_count = 10
            else:
                ds_count = 6

            lines_height = 85 * lines
            """
            `85` 为曲绘高度 `80` + 间隔 `5`
            `lines` 为行数
            `lines_height` 为各等级曲绘和间隔总和高度
            """
            
            height = 325 + ds_count * 20 + lines_height
            """
            `325` 为顶部文字和底部图片高度 + 上下间隔高度
            `ds_count * 20` 为等级数量 `ds_count` * 等级间隔 `20`
            """
            im = self._generate_rating_bg(height)

            dr = ImageDraw.Draw(im)
            sy = DrawText(dr, SIYUAN)
            ts = DrawText(dr, TBFONT)
            fot = DrawText(dr, FOTNEWRODIN)
            
            im.alpha_composite(ScoreBaseImage._design_prism_bg, (200, height - 113))
            sy.draw(
                700, height - 70, 22, 
                f"Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {maiconfig.botname} BOT", 
                ScoreBaseImage._default_text_color, "mm"
            )
            y = 100
            for _lv in lvlist: 
                x = 160
                y += 20
                im.alpha_composite(ScoreBaseImage._level_bg.resize((80, 80)), (50, y + 80))
                ts.draw(88, y + 120, 35, _lv, anchor="mm")
                for num, music in enumerate(lvlist[_lv]):
                    if num % 14 == 0:
                        x = 160
                        y += 85
                    else:
                        x += 85
                    cover = Image.open(song_chart(music.song_id)).resize((75, 75))
                    im.alpha_composite(cover, (x, y))
                    if music.type == "DX":
                        im.alpha_composite(self._dx_small_bg, (x + 31, y))
                    im.alpha_composite(self._diff_bg[music.difficulties.difficulty], (x, y + 59))
                    ts.draw(
                        x + 37, y + 67, 13, music.song_id, 
                        ScoreBaseImage._diff_text_color[music.difficulties.difficulty], "mm"
                    )
                if not lvlist[_lv]:
                    y += 85

            await self._save_image(im, rating_dir / f"{lv}.png")
            
            now_time = int(time.time() - single_time)
            log.info(f"lv.{lv} 定数表更新完成，耗时：{now_time}s")
    
    def update_plate(self):
        pass


async def update_plate_table() -> str:
    """更新完成表"""
    try:
        version = list(_ for _ in DX_VERSION.keys())[1:]
        # version.append("霸")
        # version.append("舞")
        id_bg = Image.new("RGBA", (100, 20), (124, 129, 255, 255))
        atime = 0
        for _v in version:
            _otime = time.time()
            if _v in PLATE_CN:
                _v = PLATE_CN[_v]
            ver, _ver = VERSION_MAP.get(_v, ([DX_VERSION.get(_v)], _v))
            
            music_id_list = mai.total_plate_id_list[_ver]
            music = mai.total_list.by_id_list(music_id_list)
            ralv: dict[str, list[Song]] = {lv: [] for lv in reversed(LEVEL_LIST)}

            for m in music:
                ralv[m.difficulties[3].level].append(m)

            lines = 0
            interval = 0
            for _ in ralv:
                musicnum = len(ralv[_])
                if musicnum == 0:
                    continue
                interval += 1
                remainder = musicnum % 10
                lines += (musicnum // 10) + (1 if remainder else 0)
            
            linesheight = 115 * lines + (interval - 1) * 15
            """
            `linesheight`: 各等级曲绘和间隔总和高度
            
                - `115` 为曲绘高度 `100` + 间隔 `15`
                - `lines` 为行数
                - `interval` 为各等级间隔行数
                - `(interval - 1) * 15` 为各等级间隔高度，各等级之间间隔为 `30`，所以只加 `15`
            """
            width, height = 1400, 150 + linesheight + 360
            """
            `150` 为底部图片 `design` 高度 + 上下间隔高度
            `linesheight` 为各等级曲绘和间隔总和高度
            `360` 为顶部图片 `` 高度 + 上下间隔高度
            """

            im = tricolor_gradient_prism_plus(width, height)
            
            im.alpha_composite(ScoreBaseImage._aurora_bg)
            im.alpha_composite(ScoreBaseImage._shines_bg, (34, 0))
            im.alpha_composite(ScoreBaseImage._cloud_bg, (319, height - 643))
            im.alpha_composite(ScoreBaseImage._rainbow_bottom_bg, (100, height - 343))
            for h in range((height // 358) + 1):
                im.alpha_composite(ScoreBaseImage._pattern_bg, (0, (358 + 7) * h))
            
            dr = ImageDraw.Draw(im)
            ts = DrawText(dr, TBFONT)
            sy = DrawText(dr, SIYUAN)
            im.alpha_composite(ScoreBaseImage._design_prism_bg, (200, height - 113))
            sy.draw(
                700, height - 70, 22, 
                f"Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {maiconfig.botname} BOT", 
                ScoreBaseImage._default_text_color, "mm"
            )
            y = 245
            for r in ralv:
                if _v in ["霸", "舞"]:
                    ralv[r].sort(key=lambda x: x.difficulties[-1].level_value, reverse=True)
                else:
                    ralv[r].sort(key=lambda x: x.difficulties[3].level_value, reverse=True)
                if ralv[r]:
                    y += 15
                    im.alpha_composite(ScoreBaseImage._level_bg, (65, y + 115))
                    ts.draw(113, y + 164, 35, r, anchor="mm")
                x = 200
                for num, music in enumerate(ralv[r]):
                    if num % 10 == 0:
                        x = 200
                        y += 115
                    else:
                        x += 115
                    cover = song_chart(music.song_id)
                    im.alpha_composite(Image.open(cover).resize((100, 100)), (x, y))
                    im.alpha_composite(id_bg, (x, y + 80))
                    ts.draw(x + 50, y + 88, 20, music.song_id, anchor="mm")

            by = BytesIO()
            im.save(by, "PNG")
            async with aiofiles.open(plate_dir / f"{_v}.png", "wb") as f:
                await f.write(by.getbuffer())
            _ntime = int(time.time() - _otime)
            atime += _ntime
            log.info(f"{_v}代牌子更新完成，耗时：{_ntime}s")
        result = f"完成表更新完成，耗时：{atime}s"
        log.info(result)
    except Exception as e:
        log.error(traceback.format_exc())
        result = f"完成表更新失败，Error: {e}"
    return result