import time
import traceback

import aiofiles
from PIL import Image, ImageDraw

from ...config import *
from ..domain.models.song import Song
from ..service import mai
from .base import ScoreBaseImage
from .tools import *


class UpdateTable:
    
    _type_bg = {
        "SD": Image.open(pic_dir / "SD.png").convert("RGBA"),
        "DX": Image.open(pic_dir / "DX.png").convert("RGBA")
    }
    _dx_small_bg    = _type_bg["DX"].resize((44, 16))
    _complete_bg    = Image.open(pic_dir / "complete.png").convert("RGBA")
    _id_bg          = Image.new("RGBA", (100, 20), (124, 129, 255, 255))
    _wu_id_bg       = Image.new("RGBA", (80, 15), (124, 129, 255, 255))
    _wu_rms_id_bg   = Image.new("RGBA", (80, 15), (219, 170, 255, 255))
    _diff_bg        = [
        Image.new("RGBA", (75, 15), color) for color in ScoreBaseImage._bg_color
    ]
    
    _font_color = (114, 188, 254, 255)
    
    def __init__(self):
        self.level_list = LEVEL_LIST[6:]
        self.version_list = list(_ for _ in DX_VERSION.keys())[1:]
    
    def _generate_rating_bg(self, height: int) -> Image.Image:
        """生成背景"""
        im = tricolor_gradient_prism_plus(1400, height)
        im.alpha_composite(ScoreBaseImage._aurora_bg)
        im.alpha_composite(ScoreBaseImage._shines_bg, (11, 6))
        im.alpha_composite(ScoreBaseImage._cloud_bg, (318, height - 545))
        im.alpha_composite(ScoreBaseImage._rainbow_bottom_bg, (122, height - 305))
        for h in range((height // 358) + 1):
            im.alpha_composite(ScoreBaseImage._pattern_bg, (0, (358 + 7) * h))
        im.alpha_composite(ScoreBaseImage._separator_bg, (100, 200))
        return im
    
    async def _save_image(self, im: Image.Image, path: Path):
        """保存图片到本地"""
        by = BytesIO()
        im.save(by, "PNG")
        async with aiofiles.open(path, "wb") as f:
            await f.write(by.getbuffer())
    
    async def update_level_15_rating_table(self):
        """单独绘制等级 15的定数表"""
        draw_time = time.time()
        lv15 = mai.total_level_data["15"]["15.0"]
        count = len(lv15)
        lines = (count // 3) + (1 if count % 3 else 0)
        height = 650 + lines * 450
        
        im = self._generate_rating_bg(height)
        
        dr = ImageDraw.Draw(im)
        fot = DrawText(dr, FOTNEWRODIN)
        
        fot.draw(495, 160, 70, "Level.", self._font_color, "ld", 8, (255, 255, 255, 255))
        fot.draw(750, 160, 100, "15", self._font_color, "ld", 8, (255, 255, 255, 255))
        fot.draw(
            700, height - 75, 30, 
            f"Designed by Yuri-YuzuChaN & BlueDeer233.", 
            self._font_color, "mm"
        )
        fot.draw(
            700, height - 30, 30, 
            f"Generated by {maiconfig.botname} BOT", 
            self._font_color, "mm"
        )
        
        im.alpha_composite(self._complete_bg, (251, 235))
        unknown_chart = Image.open(song_chart(0)).convert("RGBA").resize((330, 330))
        for i in range(lines * 3):
            row, col = divmod(i, 3)
            
            x = 100 + col * 425
            y = 500 + row * 450
            
            im.alpha_composite(ScoreBaseImage._chart_white_bg, (x, y))
            if i < count:
                song = lv15[i]
                chart = Image.open(song_chart(song.song_id)).convert("RGBA")
                im.alpha_composite(chart.resize((330, 330)), (x + 10, y + 10))
                im.alpha_composite(self._type_bg[song.type], (x + 200, y + 345))
                im.alpha_composite(
                    Image.open(pic_dir / f"{song.version_str}.png").resize((332, 160)), 
                    (x + 9, y - 80)
                )
                fot.draw(x + 100, y + 370, 35, song.song_id, self._font_color, "mm")
            else:
                im.alpha_composite(unknown_chart, (x + 10, y + 10))
                im.alpha_composite(self._type_bg["DX"], (x + 200, y + 345))
                fot.draw(x + 100, y + 370, 35, "????", self._font_color, "mm")
                fot.draw(x + 175, y + 280, 30, 
                    "UNKNOWN", self._font_color, "mm", 8, (255, 255, 255, 255)
                )
        
        await self._save_image(im, rating_dir / "15.png")
        log.info(f"lv.15 定数表更新完成，耗时：{time.time() - draw_time:.3f}s")
    
    async def update_rating_table(self):
        """绘制定数表"""
        for lv in self.level_list[:-1]:
            single_time = time.time()
            lvlist = mai.total_level_data[lv]
            lines = 0
            for _l in lvlist:
                song_num = len(lvlist[_l])
                if song_num == 0:
                    count = 1
                else:
                    div, remainder = divmod(song_num, 14)
                    count = div + (1 if remainder else 0)
                lines += count
            
            ds_count = 4 if "+" in lv else 6
            
            height = 650 + ds_count * 20 + 85 * lines
            """
            `325` 为顶部文字和底部图片高度 + 上下间隔高度
            `ds_count * 20` 为等级数量 `ds_count` * 等级间隔 `20`
            `85` 为曲绘高度 `80` + 间隔 `5`
            `lines` 为行数
            `lines_height` 为各等级曲绘和间隔总和高度
            """
            im = self._generate_rating_bg(height)

            dr = ImageDraw.Draw(im)
            ts = DrawText(dr, TBFONT)
            fot = DrawText(dr, FOTNEWRODIN)
            
            fot.draw(495, 160, 70, "Level.", self._font_color, "ld", 8, (255, 255, 255, 255))
            fot.draw(750, 160, 100, lv, self._font_color, "ld", 8, (255, 255, 255, 255))
            fot.draw(
                700, height - 75, 30, 
                f"Designed by Yuri-YuzuChaN & BlueDeer233.", 
                self._font_color, "mm"
            )
            fot.draw(
                700, height - 30, 30, 
                f"Generated by {maiconfig.botname} BOT", 
                self._font_color, "mm"
            )
            
            im.alpha_composite(self._complete_bg, (251, 235))
            
            GRID_STEP = 85      # 每个格子的间距 (75封面 + 10间距)
            START_X = 110       # 曲目图标起始 X
            
            start_y = 420       # 起始 Y
            for ds, songs in lvlist.items():
                _ds = ds.split(".")[-1]
                ts.draw(60, start_y + 35, 65, _ds, self._font_color, "mm", 2, (255, 255, 255, 255))

                if not songs:
                    start_y += GRID_STEP
                    continue
                
                max_row = 0
                for num, song in enumerate(songs):
                    row, col = divmod(num, 14)
                    max_row = max(max_row, row)
                    
                    x = START_X + col * GRID_STEP
                    y = start_y + row * GRID_STEP
                    
                    cover = Image.open(song_chart(song.song_id)).resize((75, 75))
                    im.alpha_composite(cover, (x, y))
                    if song.type == "DX":
                        im.alpha_composite(self._dx_small_bg, (x + 31, y))
                    im.alpha_composite(self._diff_bg[song.difficulties.difficulty], (x, y + 60))
                    ts.draw(
                        x + 37, y + 67, 13, song.song_id, 
                        ScoreBaseImage._diff_text_color[song.difficulties.difficulty], "mm"
                    )
                start_y += (max_row + 1) * GRID_STEP + 30

            await self._save_image(im, rating_dir / f"{lv}.png")
            log.info(f"lv.{lv} 定数表更新完成，耗时：{time.time() - single_time:.3f}s")
    
    def _get_level_dict(self) -> dict[str, list[Song]]:
        return {lv: [] for lv in reversed(LEVEL_LIST)}
    
    def _get_song_list(self, version_name: str) -> list[Song]:
        song_id_list = mai.total_plate_id_list[version_name]
        song_list = mai.total_list.by_id_list(song_id_list)
        return song_list
    
    async def update_wu_plate_table(self):
        """更新「霸者」/「舞」牌"""
        single_time = time.time()
        song_list = self._get_song_list("舞")
        song_id_list = mai.total_plate_id_list["舞ReMASTER"]
        remaster_song_list = self._get_song_list("舞ReMASTER")
        sum_basic = len(song_list)
        sum_remaster = len(remaster_song_list)
        
        all_level_dict = self._get_level_dict()
        
        for s in song_list:
            if s.song_id in song_id_list:
                all_level_dict[s.difficulties[4].level].append(s)
            else:
                all_level_dict[s.difficulties[3].level].append(s)
        
        keys = list(all_level_dict.keys())

        idx = keys.index("13")
        
        dict_higt = {k: all_level_dict[k] for k in keys[:idx]}
        dict_low = {k: all_level_dict[k] for k in keys[idx:]}
        
        for n, level_dict in enumerate([dict_higt, dict_low]):
            
            lines = 0
            interval = 0
            for _ in level_dict:
                song_num = len(level_dict[_])
                if song_num == 0:
                    continue
                div, remainder = divmod(song_num, 12)
                lines += div + (1 if remainder else 0)
                interval += 1
            
            linesheight = 95 * lines + (interval - 1) * 15
            height = 150 + linesheight + 360
            
            im = self._generate_rating_bg(height)
            
            dr = ImageDraw.Draw(im)
            ts = DrawText(dr, TBFONT)
            fot = DrawText(dr, FOTNEWRODIN)
            
            fot.draw(700, height - 100, 30, f"Pages {n + 1}", self._font_color, "mm")
            fot.draw(
                700, height - 75, 30, 
                f"Designed by Yuri-YuzuChaN & BlueDeer233.", 
                self._font_color, "mm"
            )
            fot.draw(
                700, height - 30, 30, 
                f"Generated by {maiconfig.botname} BOT", 
                self._font_color, "mm"
            )
            GRID_STEP = 95
            START_X = 130
            
            start_y = 245
            for ds, songs in level_dict.items():
                songs.sort(key=lambda x: x.difficulties[-1].level_value, reverse=True)
                
                if songs:
                    start_y += 15
                    ts.draw(55, start_y + 164, 35, ds, anchor="mm")
                
                max_row = 0
                for num, song in enumerate(songs):
                    row, col = divmod(num, 12)
                    max_row = max(max_row, row)
                    
                    x = START_X + col * GRID_STEP
                    y = start_y + row * GRID_STEP
                    
                    cover = song_chart(song.song_id)
                    im.alpha_composite(Image.open(cover).resize((80, 80)), (x, y))
                    if song.song_id in remaster_song_list:
                        _id_bg = self._wu_rms_id_bg
                    else:
                        _id_bg = self._wu_id_bg
                    im.alpha_composite(_id_bg, (x, y + 65))
                    ts.draw(x + 40, y + 78, 20, song.song_id, anchor="mm")
                start_y += (max_row + 1) * GRID_STEP + 15

            await self._save_image(im, plate_dir / f"舞-{n + 1}.png")
        log.info(f"舞代完成表更新完成，耗时：{time.time() - single_time:.3f}s")
    
    async def update_plate_table(self):
        all_time = 0
        for name in self.version_list:
            single_time = time.time()
            if name in PLATE_CN:
                name = PLATE_CN[name]
            ver, version_name = VERSION_MAP.get(name, ([DX_VERSION.get(name)], name))
            
            song_list = self._get_song_list(version_name)
            level_dict = self._get_level_dict()

            for s in song_list:
                level_dict[s.difficulties[3].level].append(s)

            lines = 0
            interval = 0
            for _ in level_dict:
                song_num = len(level_dict[_])
                if song_num == 0:
                    continue
                div, remainder = divmod(song_num, 10)
                lines += div + (1 if remainder else 0)
                interval += 1
            
            linesheight = 115 * lines + (interval - 1) * 15
            """
            `linesheight`: 各等级曲绘和间隔总和高度
            
                - `115` 为曲绘高度 `100` + 间隔 `15`
                - `lines` 为行数
                - `interval` 为各等级间隔行数
                - `(interval - 1) * 15` 为各等级间隔高度，各等级之间间隔为 `30`，所以只加 `15`
            """
            height = 150 + linesheight + 360
            """
            `150` 为底部图片 `design` 高度 + 上下间隔高度
            `linesheight` 为各等级曲绘和间隔总和高度
            `360` 为顶部图片 `` 高度 + 上下间隔高度
            """
            im = self._generate_rating_bg(height)
            
            dr = ImageDraw.Draw(im)
            ts = DrawText(dr, TBFONT)
            fot = DrawText(dr, FOTNEWRODIN)
            
            fot.draw(
                700, height - 75, 30, 
                f"Designed by Yuri-YuzuChaN & BlueDeer233.", 
                self._font_color, "mm"
            )
            fot.draw(
                700, height - 30, 30, 
                f"Generated by {maiconfig.botname} BOT", 
                self._font_color, "mm"
            )
            
            GRID_STEP = 115
            START_X = 200
            
            start_y = 245
            for ds, songs in level_dict.items():
                songs.sort(key=lambda x: x.difficulties[3].level_value, reverse=True)
                
                if songs:
                    start_y += 15
                    im.alpha_composite(ScoreBaseImage._level_bg, (65, start_y + 115))
                    ts.draw(113, start_y + 164, 35, ds, anchor="mm")
                x = 200
                
                max_row = 0
                for num, song in enumerate(songs):
                    row, col = divmod(num, 10)
                    max_row = max(max_row, row)
                    
                    x = START_X + col * GRID_STEP
                    y = start_y + row * GRID_STEP
                    
                    cover = song_chart(song.song_id)
                    im.alpha_composite(Image.open(cover).resize((100, 100)), (x, y))
                    im.alpha_composite(self._id_bg, (x, y + 80))
                    ts.draw(x + 50, y + 88, 20, song.song_id, anchor="mm")
                start_y += (max_row + 1) * GRID_STEP + 30

            await self._save_image(im, plate_dir / f"{name}.png")
            s_time = round(time.time() - single_time, 3)
            all_time += s_time
            log.info(f"{name}代牌子更新完成，耗时：{s_time}s")
        result = f"完成表更新完成，耗时：{all_time}s"
        log.info(result)
        return result
